### ISSUE TITLE
Internationalisierung in der ganzen Anwendung

### ISSUE THREAD

**Issue by PeterEhses** [PeterEhses/riff-terminal#10]
@Intermediadesign sollen alle Texte in der Anwendung übersetzt werden, also auch die Titel, kurztexte etc.?

**Comment by Intermediadesign** [comment]
Die Texte kommen alle bereits übersetzt. Die Anwendung muss nichts übersetzten

**Comment by PeterEhses** [comment]
@Intermediadesign Klar, die anwendung könnte auch nichts übersetzt werden. also alle texte und titel liegen in deutscher und englischer fassung vor?
Gehen wir davon aus, dass die namen / anzahl von personen / "Korallenriffe und Menschen" titel für immer(ish) gleich bleiben? Dann muss ich dafür nicht auch noch einstellungen einbauen

**Comment by PeterEhses** [comment]
bis auf #48 und alle .vtt dateien done.
