### ISSUE TITLE
Idle Video - Logic?

### ISSUE THREAD

**Issue by PeterEhses** [PeterEhses/riff-terminal#15]
@Intermediadesign Jones hat eine anzahl von verschiedenen Idle-Animationen hochgeladen. Werden die am ende in ein Video geschitten oder muss die software die hinter einander aufrufen?

**Comment by Intermediadesign** [comment]
Mann muss die vielleicht nochmal etwas in der Anzahl reduzieren. Gedacht war aber, dass die Software aus allen Personen-idels diese in zufälliger Reihenfolge abspielt. 

Anbei Text für die Auswahlseite. Ich warte aber noch auf eine Freigabe hierfür. 





Korallenriffe und Menschen 


Onyx Le Bihan
Speerfischerin auf Moorea, Tahiti

Onyx Le Bihan
Spearfisher at Moorea, Tahiti


Dr. Sebastian Ferse
Leibniz-Zentrum für Marine Tropenforschung
Executive Director Future Earth Coasts

Dr. Sebastian Ferse
Leibniz Center for Tropical Marine Research
Executive Director Future Earth Coasts


Dr. Moshira Hassan
Reef Check Koordinatorin Deutschland/Europa und
Rotes Meer

Dr. Moshira Hassan
Reef Check Coordinator Germany/Europe and Red Sea


Claudia Schmitt
The Jetlagged

Claudia Schmitt
The Jetlagged


Taiano Teiho
Coral-Gardener auf Moorea, Tahiti

Taiano Teiho
Coral gardener at Moorea, Tahiti
---
Prof. Daniel Gilgen
Fachrichtungsleitung
Intermedia Design 

Hochschule Trier 
Campus Gestaltung 
Irminenfreihof 8
D-54293 Trier

**Comment by PeterEhses** [comment]
Mir wird langsam klar warum sich die illuminate Programmierer von dir
fernhalten 😂
Du musst so Sachen direkt in den spec schreiben.. Macht keinen Spaß sich
den selbst zusammen zu basteln.

Danke für die Texte!
