### ISSUE TITLE
Set side for projection blurb texts

### ISSUE THREAD

**Issue by PeterEhses** [PeterEhses/riff-terminal#3]
Have projection blurb specific to one side.

Todo:
What happens to texts without defined side? What happens if one side doesn't have enough texts?

**Comment by Intermediadesign** [comment]
equally amount of text will be provided for each Person. No grey untertitels needed.

**Comment by PeterEhses** [comment]
Stimmt die Untertitel gab es ja auch noch.
Wie ist das dann? Gibt es noch die lokalisieren texte? Ist alles auf deutsch?

**Comment by Intermediadesign** [comment]
Hi Peter, 

alles ist immer zweisprachig: deutsch / englisch  

Die Untertitel kommen von Jonas 

D.

**Comment by PeterEhses** [comment]
@Intermediadesign Achtung, das hier ist ein issue zur projektion, nicht den interviews. Ich glaube in den mails steht das nicht immer klar? Am besten funktioniert github in der app bzw. website. 
Also wird es auch de / en übersetzungen für die projektions-bubbles geben?
